services:
  app:
    container_name: setup-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - POSTGRES_PRISMA_URL=postgres://avnadmin:AVNS_sNrH0bbgljevhJqmzoo@eventoplanejado-eventoplanejado.k.aivencloud.com:18625/defaultdb?sslmode=require&pgbouncer=true&connect_timeout=15
      - POSTGRES_URL_NON_POOLING=postgres://avnadmin:AVNS_sNrH0bbgljevhJqmzoo@eventoplanejado-eventoplanejado.k.aivencloud.com:18625/defaultdb?sslmode=require
    ports:
      - 3000:3000