name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITHUB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy with ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_REMOTE_SERVER_IP }}
          username: root
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            whoami
            ls -la
            pwd
            cd /home/evento_planejado_api/eventoplanejadoserver/
            export GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa'
            git pull origin main
            git status
            npm install
            npm run build
            pm2 restart 0
