name: "Deploy para VPS"
on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs: 
  build_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Deploy with ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "167.88.39.32"
          username: root
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE}}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/evento_planejado_api/eventoplanejadoserver/
            git pull origin main
            git status
            npm install
            npm run build
            pm2 restart api_evento_planejado_server
        